### ISSUE TITLE
support for latte-dock

### ISSUE THREAD

**Issue by kupiqu** [paju1986/PlasmaConfSaver#1]

**Comment by paju1986** [comment]
hello.

What do you mean with latter-dock support?

**Comment by kupiqu** [comment]
Latte-dock uses its own config files, so it would be great that PlasmaConfSaver would also be able to store and restore different Latte-dock configurations.

EDIT: Ideally storing together plasma+latte as a pack in each configuration of a plasma desktop

**Comment by paju1986** [comment]
Ok, im working on it. it will backup the latte config files and then it will check if latte-dock was running when it saved the config so it can run it again at restore.

**Comment by kupiqu** [comment]
Awesome, thanks!

**Comment by paju1986** [comment]
Implemented, please test

**Comment by kupiqu** [comment]
It seems to work: even though latte-dock crashed, on restart, it was restored correctly

**Comment by paju1986** [comment]
closing the issue

**Comment by kupiqu** [comment]
Thank you for implementing.

Re latte crash: not sure how you are restarting latte, the recommended way is `latte-dock --replace`. this may fix the crash if you are doing differently...

**Comment by paju1986** [comment]
you are right, that is a better way of restarting it, i changed the code, the fix will go with the next version release. thanks you

**Comment by kupiqu** [comment]
Sure, no problem. Btw, same thing applies to plasmashell.
