### ISSUE TITLE
[Suggestion] Change the busy indicator to make it feel more integrated

### ISSUE THREAD

**Issue by magnuslarsen** [paju1986/PlasmaConfSaver#11]
To make this widget "feel" more integrated into KDE, I would suggest changing the GIF busy indicator to the one KDE / Plasma 5 uses about everywhere.

I found some KDE issues about this, that may be of help:
https://phabricator.kde.org/D23155
https://phabricator.kde.org/D22630

I see those aren't GIFs, but pure QML, so it would require a little coding. But the result would be:
1. Feel more integrated 
2. Less choppy

**Comment by paju1986** [comment]
Yes, it should be better, I will try to look into it this weekend.

**Comment by paju1986** [comment]
done, in repo now, will be on the latest version once released
