### ISSUE TITLE
Problemas con exportación-importación y vista previa

### ISSUE THREAD

**Issue by srpaquito** [paju1986/PlasmaConfSaver#2]
Hola Alberto.

Soy el Señor Paquito y hemos hablado en los comentarios de la noticia sobre tu plasmoide que se publicó en KDE Blog.

El caso es que el plasmoide se ve y funciona en mi sistema igual que lo hacía en la primera versión que probé, es decir, no hay ni utilidad de importar-exportar configuración ni tampoco hay vistas previas.

En KDE Blog me recomendaste instalar el paquete scrot. Lo hice, pero no funcionó.

Hay que resaltar que, por si acaso, desinstalé el plasmoide, que había instalado desde el archivo y lo volví a instalar luego desde la propia ulitidad para instalar los plasmoides. El resultado es el que te conté antes.

Por cierto, te recuerdo que mi sistema es un KDE Neon 18.04.

Gracias.

**Comment by paju1986** [comment]
Hola.

Prueba a desinstalar el plasmoide y asegurate de que descargas el plasmoide desde esta direccion: 

https://www.opendesktop.org/p/1298955/startdownload?file_id=1555522546&file_name=com.pajuelo.plasmaConfSaver-0.8.tar.gz&file_type=application/x-gzip&file_size=11344

Luego descomprimelo en /home/[tu usuario]/.local/share/plasma/plasmoids y cierra sesión y vuelve a entrar.

Mira a ver si así te sigue pasando.

**Comment by srpaquito** [comment]
Hola otra vez.

Instrucciones aplicadas y problema resuelto.

Además, de paso he aprendido como inistalar plasmoides manualmente.

Muchas gracias.

**Comment by paju1986** [comment]
Estupendo, cierro la incidencia.
