### ISSUE TITLE
Kvantum support?

### ISSUE THREAD

**Issue by miraclx** [paju1986/PlasmaConfSaver#20]
Would be nice to be able to save, restore and activate kvantum themes

Is this a feature coming soon?

**Comment by paju1986** [comment]
Will look into it, i think shouldnt be too complicated

**Comment by miraclx** [comment]
Yeah, `$HOME/.config/Kvantum/` is a good starting point

**Comment by paju1986** [comment]
Added kvamtum support on version 1.5
