### ISSUE TITLE
import/export doesnt work

### ISSUE THREAD

**Issue by HarkTu** [paju1986/PlasmaConfSaver#25]
manjaro 20.2, kde plasma 5.20.4
I used to use alot confsaver v1.2 before. new versions looks like bugged and cant find the old version.

**Comment by sparshg** [comment]
Have you tried installing kdialog listed https://store.kde.org/p/1298955/
```
REQUERIMENTS:
scrot
spectacle
kdialog
Konsole
Qt.labs.platform
```

**Comment by AnthonyLzq** [comment]
I had the same problem, now it works after installing the dependencies.

**Comment by HarkTu** [comment]
Installing dependencies solved the issue, thanks.
