### ISSUE TITLE
Translation for French

### ISSUE THREAD

**Issue by Gspohu** [paju1986/PlasmaConfSaver#3]
Hello,

I saw the message for version 0.13, where you asked for the widget translation. So, you will find attached to this issue the template.pot translated into French, which is my mother tongue.

[template.zip](https://github.com/paju1986/PlasmaConfSaver/files/3179693/template.zip)

Bye,

**Comment by paju1986** [comment]
Thanks you! Will be added for the next version

**Comment by paju1986** [comment]
Included on git version thanks you
