### ISSUE TITLE
Reguarding the translation scripts

### ISSUE THREAD

**Issue by Zren** [paju1986/PlasmaConfSaver#9]
* You will need to rename `portuguese.pot` to `pt.po` (or `pt_BR.po` if it's only the brazillian dialect). The `.pot` file extension is for the `template.pot`. The `translate/merge` script will only merge the updated `template.pot` messages into `*.po` files. We also need to change "portuguese" in the filename to the locale code "pt" since the merge script uses it to generate the `contents/locale/` directory.

```bash
cd com.pajuelo.plasmaConfSaver/translate/
git mv ./portuguese.pot ./pt_BR.po
```

* You should update the `translate/ReadMe.md` to change the links from "presentwindows" to your github repo. A user mistakenly clicked it and uploaded Turkish translations for your widget to my repo. https://github.com/Zren/plasma-applet-presentwindows/issues/7

**Comment by paju1986** [comment]
Done, thanks you for pointing out.

**Comment by Zren** [comment]
Also, you will need to update the `merge` script to v10 to support the turkish `tr.po`. Perl didn't treat the `tr` as a string, so I needed to add quotes `"tr"`.

* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/translate/merge
* https://github.com/Zren/plasma-applet-eventcalendar/commit/32c8be90b808c0969a4cd5808faf89ccd7fb170d

The version of `plasmoidlocaletest` in this repo of can test `tr.po` with: `./plasmoidlocaletest tr_TR:tr`

Though `plasmoidlocaletest` v5 can run it with `./plasmoidlocaletest tr`

https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/translate/plasmoidlocaletest
